apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grid-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.hub.ingress.host }}
      http:
        paths:
          - path: /ui
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-hub
                port:
                  number: {{ .Values.service.port }}

          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-hub
                port:
                  number: {{ .Values.service.port }}

          - path: /wd/hub
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-hub
                port:
                  number: {{ .Values.service.port }}

          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-hub
                port:
                  number: {{ .Values.service.port }}
